global:
  rbac:
    create: true

prometheusOperator:
  logLevel: debug

prometheus:
  ingress:
    enabled: true
    # @TODO change
    hosts:
      - {{ monitoring.prometheus.host }}
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: "servers"
        static_configs:
          - targets:
{% for target in monitoring.node_targets %}
            - "{{ target }}:9100"
{% endfor %}
      - job_name: "snmp"
        static_configs:
          - targets:
{% for target in monitoring.snmp_targets %}
            - {{ target }}
{% endfor %}
        metrics_path: /snmp
        params:
          module:
            - if_mib
            - ip_forward_mib
            - sw_arista
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: prometheus-snmp-exporter:9116

    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: local-path
          resources:
            requests:
              # As already noted, local path does not really care
              storage: 75Gi

grafana:
  adminPassword: lanarama
  ingress:
    enabled: true
    # @TODO change
    hosts:
      - {{ monitoring.grafana.host }}
  persistence:
    enabled: true
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    # Same as for prometheus
    size: 5Gi

# Alertmanager
alertmanager:
  enabled: true
  ingress:
    enabled: true
    # @TODO change
    hosts:
      - {{ monitoring.alertmanager.host }}
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: local-path
          resources:
            requests:
              storage: 5Gi

# Already running!
nodeExporter:
  enabled: false 