---
- name: install dhcp package
  package:
    name: isc-dhcp-server
    state: present

# DHCP
- name: DHCP-server configuration
  template:
    src: dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
    #
# DHCP
- name: Defaults to only enable IPv4 DHCPd
  template:
    src: defaults
    dest: /etc/default/isc-dhcp-server
    owner: root
    group: root
    mode: 0644
    backup: yes

# DHCP
- name: Enable dhcp server
  service:
    name: isc-dhcp-server
    state: restarted
    enabled: yes
