---
- name: generate interface configuration
  template:
    src: interfaces
    dest: /etc/network/interfaces
  register: interfaces_conf

- name: copy quagga static configuration
  copy:
    src: "{{ item }}"
    dest: "/etc/quagga/{{ item }}"
  with_items:
    - zebra.conf
    - bgpd.conf
    - daemons
  register: quagga_static_conf

- name: generate quagga configuration
  template:
    src: Quagga.conf
    dest: /etc/quagga/Quagga.conf
  register: quagga_conf

- name: generate dhcp relay configuration
  template:
    src: isc_dhcp_relay
    dest: /etc/default/isc-dhcp-relay
  register: isc_dhcp_relay_conf

- name: generate snmpd configuration
  template:
    src: snmpd.conf
    dest: /etc/snmp/snmpd.conf
  register: snmp_config

- name: Restart and enable switchd
  sysvinit:
    name: switchd
    state: restarted
    enabled: yes
  when: interfaces_conf.changed

- name: Restart and enable quagga
  sysvinit:
    name: quagga
    state: restarted
    enabled: yes
  when: quagga_conf.changed or quagga_static_conf.changed

- name: Restart and enable isc dhcp relay
  sysvinit:
    name: isc-dhcp-relay
    state: restarted
    enabled: yes
  when: isc_dhcp_relay_conf.changed

- name: Start and enable snmpd
  sysvinit:
    name: snmpd
    state: started
    enabled: yes

- name: Restart snmpd
  sysvinit:
    name: snmpd
    state: restarted
  when: snmp_config.changed