all:
  children:
    vm_hosts:
      hosts:
        kvm0:
          ansible_host: 172.16.0.162
          ansible_python_interpreter: /usr/bin/python3
    gateways:
      hosts:
        heaven0:
          ansible_host: 172.16.0.162
          ansible_python_interpreter: /usr/bin/python3
