all:
  children:
    vm_hosts:
      hosts:
        kvm0:
          ansible_host: kvm0
          ansible_python_interpreter: /usr/bin/python3
    gateways:
      hosts:
        heaven0:
          ansible_host: heaven0
          ansible_python_interpreter: /usr/bin/python3
