all:
  children:
    dhcpd:
      hosts:
        vm01:
          ansible_host: vm01
          ansible_python_interpreter: /usr/bin/python3
    dnsd:
      hosts:
        vm02:
          ansible_host: vm02
          ansible_python_interpreter: /usr/bin/python3
    monitoring:
      hosts:
        k8s:
          ansible_host: k8s
          ansible_python_interpreter: /usr/bin/python3