all:
  children:
    dhcpd:
      hosts:
        vm01:
          ansible_host: vm01
          ansible_python_interpreter: /usr/bin/python3
    monitoring:
      hosts:
        vm03:
          ansible_host: vm03
          ansible_python_interpreter: /usr/bin/python3
