- name: download helm
  become: false
  get_url:
    url: "https://get.helm.sh/helm-{{ k8s.helm.version }}-linux-amd64.tar.gz"
    dest: "/tmp/helm-{{ k8s.helm.version }}.linux-amd64.tar.gz"
  retries: 3
  delay: 1
  delegate_to: localhost

- name: unpack helm binary
  become: false
  unarchive:
    src: "/tmp/helm-{{ k8s.helm.version }}.linux-amd64.tar.gz"
    dest: /tmp
    creates: "/tmp/linux-amd64/helm"
  delegate_to: localhost

- name: create /usr/local/bin
  file:
    path: /usr/local/bin
    state: directory
    mode: 0755

- name: copy helm binary to /usr/local/bin
  copy:
    src: "/tmp/linux-amd64/helm"
    dest: /usr/local/bin/helm
    mode: 0755

# - name: Create service account
#   shell: |
#     kubectl -n kube-system create serviceaccount tiller

# - name: Create clusterrole binding
#   shell: |
#     kubectl create clusterrolebinding tiller \
#       --clusterrole=cluster-admin \
#       --serviceaccount=kube-system:tiller

- name: initialize helm
  shell: |
    helm init --service-account tiller