---
- name: Check if k3s exists
  stat:
    path: /usr/local/bin/k3s
  register: k3s_installed

- name: Install curl
  package:
    name:
      - curl
    state: present

- pip:
    name:
      - openshift
      - pyhelm
    state: present

- name: Install k3s single node cluster
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--no-deploy traefik" sh -

- name: Wait for k3s
  wait_for:
    host: 127.0.0.1
    port: 6443
    state: started

- name: create /root/.kube
  file:
    path: /root/.kube
    state: directory
    mode: 0700

- name: Copy kubeconfig
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    remote_src: yes
    dest: /root/.kube/config

- name: Install local-path storage provisioner
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml

- include: helm.yaml

- name: traefik helm override
  template:
    src: traefik_values.yaml
    dest: /opt/traefik_values.yaml
  register: traefik_values

- name: install traefik
  shell: |
    helm install --namespace kube-system --name traefik \
      -f /opt/traefik_values.yaml \
      stable/traefik
  register: helm_install

- name: upgrade traefik
  shell: |
    helm upgrade traefik -f /opt/traefik_values.yaml stable/traefik
  when:
    - traefik_values.changed