---
- name: create monitoring network
  docker_network:
    name: monitoring
    state: present

- name: create prometheus volume
  docker_volume:
    name: prometheus_data
    state: present

- name: prometheus configuration
  template:
    src: prometheus.yml
    dest: /etc/prometheus.yml
    mode: 0644
  register: prometheus_config

- name: create snmp exporter
  docker_container:
    name: snmp_exporter
    image: "quay.io/prometheus/snmp-exporter:v{{ monitoring.snmp_exporter_version }}"
    networks_cli_compatible: yes
    networks:
      - name: monitoring
    state: started
    restart: yes

- name: create prometheus container
  docker_container:
    name: prometheus
    image: "quay.io/prometheus/prometheus:v{{ monitoring.prometheus_version }}"
    volumes:
      - prometheus_data:/prometheus
      - /etc/prometheus.yml:/etc/prometheus/prometheus.yml
    networks_cli_compatible: yes
    networks:
      - name: monitoring
      - name: "{{ traefik.docker_network }}"
    published_ports:
      - 127.0.0.1:9090:9090
    labels:
      traefik.enable: "true"
      traefik.docker.network: "{{ traefik.docker_network }}"
      traefik.prometheus.frontend.rule: "Host:{{ monitoring.prometheus_hostname }}"
      traefik.prometheus.port: "9090"

    state: started
    restart: yes
    # dns_servers:
    #   - "{{ monitoring.dns }}"

- name: restart prometheus container
  command: docker restart prometheus
  when: prometheus_config.changed
