# Lanarama Prometheus config

global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      name: "Lanarama Infrastructure Monitoring"

scrape_configs:

  - job_name: "node"
    static_configs:
      - targets:
{% for target in monitoring.node_targets %}
        - "{{ target }}:9100"
{% endfor %}

  - job_name: "snmp"
    static_configs:
      - targets:
{% for target in monitoring.snmp_targets %}
        - {{ target }}
{% endfor %}
    metrics_path: /snmp
    params:
      module:
        - if_mib
        - ip_forward_mib
        - sw_arista

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp_exporter:9116

