frr:

  hostname: heaven0

  # IP Address configuration
  interfaces:
    - name: enp8s0f1
      ipv4:
        - 10.51.1.2/30
      ipv6:
        - fc00:0:511::2/126
    - name: enp8s0f0
      ipv4:
        - 10.151.1.2/30
      ipv6:
        - fc00:1:511::2/126
    - name: lo
      ipv4:
        - 10.64.50.1/32

  # BGP Configuration
  bgp:
    # Local AS + Router ID
    local_as: 65001
    router_id: 10.64.50.1

    # BGP Peers
    neighbors:
      - addr: fc00:0:511::1
        remote_as: 64666
      - addr: fc00:1:511::1
        remote_as: 64667

    # Advertised networks
    networks:
      ipv4:
        # This is our main gateway, advertise default route
        - 0.0.0.0/0
      ipv6:

  # Static routes
  static:
    v4:
      # kvm0 internet access :-)
      - dest: 10.52.1.2/32
        next_hop: 10.51.1.1
      - dest: 10.152.1.2/32
        next_hop: 10.151.1.1
    v6:
