frr:

  hostname: kvm0

  # IP Address configuration
  interfaces:
    - name: enp8s0f0
      ipv4:
        - 10.52.1.2/30
      ipv6:
        - fc00:0:512::2/126
    - name: enp8s0f1
      ipv4:
        - 10.152.1.2/30
      ipv6:
        - fc00:1:512::2/126
    - name: lo
      ipv4:
        - 10.64.80.1/32

  # BGP Configuration
  bgp:
    # Local AS + Router ID
    local_as: 64801
    router_id: 10.64.80.1

    # BGP Peers
    neighbors:
      - addr: fc00:0:512::1
        remote_as: 64666
      - addr: fc00:1:512::1
        remote_as: 64667

    # Advertised networks
    networks:
      ipv4:
        - 10.64.80.1/32
        - 192.168.122.0/24
      ipv6:
