network:
  dhcp:
    interfaces:
      - name: eth0
      - name: eth1
  bgp:
    enabled: no
  # v4:
  #   ip: 172.17.0.1/24
  # v6:
  #   ip: fc13:37::1/64
  # interfaces:
  #   - name: eth2
  #   - name: eth3
  static:
  # interfaces:
  #     - name: none
  #       v4:
  #         ip: 10.0.0.101/24
  #         gateway: 10.0.0.1
  #       v6:
  #         ip: fe80::101
  #         netmask: 64
  #         gateway:  fe80::1
