#coredns: For some reason it can't find the variables if it is grouped by role?
  coredns_version: 1.6.2
  coredns_port: 53

  coredns_system_group: "coredns"
  coredns_system_user: "{{ coredns_system_group }}"
    
  go_arch_map:
    i386: '386'
    x86_64: 'amd64'
    aarch64: 'arm64'
    armv7l: 'armv7'
    armv6l: 'armv6'

  go_arch: "{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}"
